"""empty message

Revision ID: cf7df53f0bec
Revises: 
Create Date: 2021-03-28 19:58:28.157536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7df53f0bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.Enum('foot', 'bike', 'car', name='couriertypeenum'), nullable=True),
    sa.Column('regions', sa.PickleType(), nullable=True),
    sa.Column('working_hours', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('courier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couriers')
    # ### end Alembic commands ###
